#!/bin/sh

set -e
set -o pipefail

# Ensure that the NPM_AUTH_TOKEN secret is included
if [[ -z "$NPM_AUTH_TOKEN" ]]; then
  echo "Set the NPM_AUTH_TOKEN env variable."
  exit 1
fi

# Copied from https://github.com/actions/npm/blob/master/entrypoint.sh
# Respect NPM_CONFIG_USERCONFIG if it is provided, default to $HOME/.npmrc
NPM_CONFIG_USERCONFIG="${NPM_CONFIG_USERCONFIG-"$HOME/.npmrc"}"
NPM_REGISTRY_URL="${NPM_REGISTRY_URL-registry.npmjs.org}"
NPM_STRICT_SSL="${NPM_STRICT_SSL-true}"
NPM_REGISTRY_SCHEME="https"
if ! $NPM_STRICT_SSL
then
  NPM_REGISTRY_SCHEME="http"
fi

# Allow registry.npmjs.org to be overridden with an environment variable
printf "//%s/:_authToken=%s\\nregistry=%s\\nstrict-ssl=%s" "$NPM_REGISTRY_URL" "$NPM_AUTH_TOKEN" "${NPM_REGISTRY_SCHEME}://$NPM_REGISTRY_URL" "${NPM_STRICT_SSL}" > "$NPM_CONFIG_USERCONFIG"

chmod 0600 "$NPM_CONFIG_USERCONFIG"

FILE=/release-workflow-tag
if [ ! -f $FILE ]; then
  echo "Publishing to @latest"
  npm publish
else
  TAG=$(cat $FILE)
  echo "Publishing to @${TAG}"
  npm publish --tag $TAG
fi
